project:
  type: book

book:
  title: "quarto_template_ugent"
  subtitle: "Academic year: 2025 - 2026"
  author: 
    name: Olivier Bonte
    affiliation: Ghent University
    email: olivier.bonte@ugent.be  
  date: today
  downloads: [pdf]
  repo-url: https://github.com/olivierbonte/quarto_template_ugent
  navbar: 
    title: "quarto_template_ugent"
    search: true 
    logo: "figures/logo_H-CEL_no_background.svg"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
jupyter: python3

format:
  html:
    theme:
      - cosmo
      - brand
    code-overflow: wrap
    code-fold: show
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex

# Allows caching of notebooks when previewing 
execute:
  cache: true
  freeze: auto
