on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 1.7.32
          tinytex: true
          
      - name: Setup Python with Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: quarto_template
          auto-activate-base: false 
      
      - name: Chromium install available to conda
        shell: bash -el {0}
        run: quarto install chromium #conda install -c conda-forge -y chromium

      - name: Check Quarto and dependencies
        shell: bash -el {0}
        run: quarto check

      - name: Render and Publish
        shell: bash -el {0}
        env:
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
        run: quarto publish quarto-pub --no-browser --no-prompt